### ISSUE TITLE
维度错误

### ISSUE THREAD

**Issue by lizhiteng111** [BIT-DYN/OpenObj#1]
Hello, thank you for your work. I encountered the following issue while running the maskgen.py file.
   x = x if start_pos > 0 else torch.cat([prompts, x], dim=1)
RuntimeError: Tensors must have same number of dimensions: got 4 and 3
I checked, and the error occurs at the following location in the code:
![image](https://github.com/user-attachments/assets/59aed37b-35ad-49d8-8184-cf0c8d960c31)
The dimension of sem_tokens is torch.Size([24, 1, 1,256])。The dimension of outputs["sem_tokens"][mask_index] is torch.Size([24, 1,256])

**Comment by BIT-DYN** [comment]
Hello, @lizhiteng111 
Strangely enough, it is working fine on our  server.
Looking at your reported error, the problem seems to be with the
`captions = tap_model.generate_text(sem_tokens)`
`sem_tokens` is just a variable that is assigned a value, maybe you should provide some more information.
