### ISSUE TITLE
visualization error: "No such file or directory: '/data/dyn/object/vmap/semantic_mapping.yaml'." 

### ISSUE THREAD

**Issue by amaozq** [BIT-DYN/OpenObj#2]
Hi,
Thank you for your excellent work! I’ve nearly completed reproducing the project, but I encountered an error during visualization: "No such file or directory: '/data/dyn/object/vmap/semantic_mapping.yaml'."

**Comment by BruceKnife** [comment]
Hello! Thank you for your support!
We missed uploading the `semantic_mapping.yaml` file earlier, and I apologize for the oversight. I have re-uploaded the file to the visualization folder. For the Replica dataset, the corresponding file is now `replica_color.yaml` (which was previously `semantic_mapping.yaml`), and for the Scannet dataset, it is `scannet_color.yaml`. I have also modified the paths to these two YAML files in the code to relative paths, so it should work correctly now!
![1](https://github.com/user-attachments/assets/91638933-7d0e-43da-a7e1-3d517b9837c6)
